### PR TITLE
Fail test if no function called after expectRevert

### LINKED ISSUE #270: expectRevert does not fail test if no contract call is made
If no contract call is made after calling `expectRevert`, the test passes, which does not seem like correct expected behavior. 

```
interface Vm {
    function expectRevert(bytes calldata) external;
}

contract Foo {
}

contract FooTest {
    Vm vm = Vm(0x7109709ECfa91a80626fF3989D68f67F5b1DD12D);
    Foo foo;
    
    function setUp() public {
        foo = new Foo();
    }

    function testBar() public {
        vm.expectRevert("message");
    }
}
```

### PR DESCRIPTION
**Pull request by wilsoncusack**
This PR fixes #270, ensuring that tests fail if expectRevert is called with no function call afterward. 

TODO: Test! Curious how this should be tested / where related tests live.

### CODE REVIEW

**Comment by brockelmore** [comment]
you should add a `testFail` to cheatcodes.sol in evm-adapters/testdata that has an incomplete `expectRevert` as a test

File: evm-adapters/src/lib.rs [hunk 1]
```diff
@@ -52,6 +52,8 @@ pub trait Evm<State> {
     /// Gets the revert reason type
     fn revert() -> Self::ReturnReason;
 
+    fn expected_revert(&self) -> Option<Vec<u8>>;
```
Comment (gakonst) [inline evm-adapters/src/lib.rs:55]: I'd return an `Option<&[u8]>` to avoid the clone in implementations

File: evm-adapters/src/sputnik/cheatcodes/cheatcode_handler.rs [hunk 2]
```diff
@@ -77,6 +77,10 @@ impl<'a, 'b, B: Backend, P: PrecompileSet> SputnikExecutor<CheatcodeStackState<'
         self.handler.config()
     }
 
+    fn expected_revert(&self) -> Option<Vec<u8>> { 
+       self.handler.state().expected_revert.clone()
```
Comment (gakonst) [inline evm-adapters/src/sputnik/cheatcodes/cheatcode_handler.rs:81]: you can do this instead to get an option to the reference
```suggestion
       self.handler.state().expected_revert.as_ref()
```

**Review by gakonst — CHANGES_REQUESTED** [review]

File: evm-adapters/src/lib.rs (hunk 1 above)
Comment (wilsoncusack) [reply evm-adapters/src/lib.rs:55]: OK. Rust n00b questions, why not `Option<&Vec<u8>>` ?

Comment (gakonst) [reply evm-adapters/src/lib.rs:55]: Don't have a good answer, more idiomatic AFAIK. Maybe @mattsse

File: evm-adapters/src/sputnik/cheatcodes/cheatcode_handler.rs (hunk 2 above)
Comment (wilsoncusack) [reply evm-adapters/src/sputnik/cheatcodes/cheatcode_handler.rs:81]: Somebody help me 😀 
```
fn expected_revert(&self) -> Option<&[u8]> { 
        let a: &Vec<u8> = self.handler.state().expected_revert.as_ref().unwrap();
        let c: &[u8] = a;
        return Some(c);
     }
```

Comment (wilsoncusack) [reply evm-adapters/src/sputnik/cheatcodes/cheatcode_handler.rs:81]: surely there is a better way

Comment (wilsoncusack) [reply evm-adapters/src/sputnik/cheatcodes/cheatcode_handler.rs:81]: er, better, but still seems should be simpler
```
fn expected_revert(&self) -> Option<&[u8]> { 
        if let Some(a) = self.handler.state().expected_revert.as_ref() {
            let c: &[u8] = a;
            return Some(c);
        }
        return None
    }
```

**Comment by wilsoncusack** [comment]
@brockelmore added test but it is not passing 🤔
Screen Shot 2021-12-20 at 3 04 50 PM

File: evm-adapters/src/sputnik/cheatcodes/cheatcode_handler.rs [hunk 3]
```diff
@@ -89,6 +85,15 @@ impl<'a, 'b, B: Backend, P: PrecompileSet> SputnikExecutor<CheatcodeStackState<'
...
     }
 
+    fn expected_revert(&self) -> Option<&[u8]> { 
+        if let Some(a) = self.handler.state().expected_revert.as_ref() {
+            let c: &[u8] = a;
+            return Some(c);
+        }
+        return None
+        
+     }
```
Comment (gakonst) [inline evm-adapters/src/sputnik/cheatcodes/cheatcode_handler.rs:95]: This should work:
```suggestion
self.handler.state().expected_revert.as_deref()
```

File: forge/src/runner.rs [hunk 4]
```diff
@@ -258,7 +258,8 @@ impl<'a, S: Clone, E: Evm<S>> ContractRunner<'a, S, E> {
                 }
             },
         };
-        let success = self.evm.check_success(self.address, &status, should_fail);
+        let success = self.evm.check_success(self.address, &status, should_fail) && self.evm.expected_revert().is_none();
```
Comment (gakonst) [inline forge/src/runner.rs:261]: I'd pull in the `self.evm.expected_revert().is_none()` check inside `check_success`

**Review by gakonst — CHANGES_REQUESTED** [review]

File: forge/src/runner.rs (hunk 4 above)
Comment (wilsoncusack) [reply forge/src/runner.rs]: nice! test is passing now :)
