### PR TITLE
fix: various trace fixes

### LINKED ISSUE #1057: REVM Tracing Followups
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (e881b75 2022-03-25T00:06:50.568028+00:00)

### What command(s) is the bug in?

forge t -vvvv

### Operating System

macOS (M1)

### Describe the bug

Tracing doesn't seem to always decode correctly. Take for example lil-web3: https://github.com/m1guelpf/lil-web3/

## ECRECOVER doesn't get decoded

The following is a call to Ecrecover which we are not decoding. I think we should be decoding it, independently of concerns about new precompiles added in L2s etc.

```
0x0000…0001::e9435c05(aa81190ba1e7e19f6372616fa7b535045c95be4afcfe0412f0fd9158000000000000000000000000000000000000000000000000000000000000001cc86807a88242d73ca11a9cfb15f54b4ea3793429728ed741d7ca77b17820637b781fb4e20122cda8916eb6dc52e950029dc2e3f5e18c34c87e636a41b9ef7c32)

```

```bash
$ forge t -vvvv -m testRevertsWhenCallReverts 
```

Output

image

## Contract ABI Functions & Events are not decoded

```
 forge t -m testCanSplitToken -vvvv --force
```
image

I've confirmed this is not a caching issue by usage of the `--force` flag and by `rm -rf`'ing the cache. I tried [moving](https://github.com/m1guelpf/lil-web3/blob/main/src/test/LilFractional.t.sol#L39) the `new TestNFT()` call from `setUp()` to the constructor, and it didn't seem to change anything, so the fuzzy deploy logic seems to be OK.

I wonder if this has to do with using the ERC721 as a dependency, vs explicitly declaring it in the contract?

### PR DESCRIPTION
**Pull request by onbjerg**
Sometimes contracts were not identified in traces because there were multiple contracts with the same name and `known_contracts` (which we use for lookups) was indexed by the contract name and nothing more.

First I thought we could just index by `artifact_id.slug()` but both of these contracts had the same slug as well, so now `known_contracts` is indexed by `ArtifactId`. This required changes in the linking step as well as the debugger.

Another issue mentioned in #1057 was that precompiles were not decoded, which will also be addressed in this PR.

**Remaining tasks**

- [x] Adjust `forge run` to new `known_contracts` type (blocked by https://github.com/gakonst/ethers-rs/pull/1080)
- [x] Decode precompile calls

Closes #1057

### CODE REVIEW

File: utils/src/lib.rs [hunk 1]
```diff
@@ -884,106 +988,6 @@ pub fn abi_to_solidity(contract_abi: &Abi, mut contract_name: &str) -> Result<St
     })
 }
 
-#[derive(Debug)]
```
Comment (onbjerg) [inline utils/src/lib.rs:887]: I just moved up this part of the linking step so I didn't have to scroll as much

File: utils/src/lib.rs [hunk 2]
```diff
@@ -1024,23 +1028,35 @@ mod tests {
...
+                .iter()
+                .find(|(i, _)| i.slug() == "Lib.json:Lib")
+                .unwrap()
+                .1
                 .bytecode
                 .clone()
                 .expect("library had no bytecode")
                 .object
                 .into_bytes()
                 .expect("could not get bytecode as bytes"),
```
Comment (onbjerg) [inline utils/src/lib.rs:1053]: image

File: evm/src/trace/decoder.rs [hunk 3]
```diff
@@ -39,6 +41,78 @@ impl CallTraceDecoder {
...
+                    5,
+                    "modexp",
+                    [
+                        ParamType::Uint(256),
+                        ParamType::Uint(256),
+                        ParamType::Uint(256),
+                        ParamType::Bytes,
+                    ],
+                    [ParamType::Bytes],
+                ),
```
Comment (onbjerg) [inline evm/src/trace/decoder.rs:71]: I am not sure this will decode because the format is a little strange, so it will show up as `PRECOMPILE::modexp(big ass blob)`

Comment (mattsse) [reply evm/src/trace/decoder.rs:71]: I wrote a HexDisplay helper on the node PR
https://github.com/gakonst/foundry/blob/243c5048016e068b8d09667899910591a9f73d00/node/src/eth/util.rs
that only prints certain lengths, maybe useful here as well?

File: evm/src/trace/decoder.rs [hunk 4]
```diff
@@ -39,6 +41,78 @@ impl CallTraceDecoder {
     /// as DSTest-style logs.
     pub fn new() -> Self {
         Self {
+            // TODO: These are the Ethereum precompiles. We should add a way to support precompiles
+            // for other networks, too.
```
Comment (mattsse) [inline evm/src/trace/decoder.rs:45]: great, let's track that separately

File: forge/src/multi_runner.rs [hunk 5]
```diff
@@ -55,18 +55,13 @@ impl MultiContractRunnerBuilder {
...
-
-        let mut known_contracts: BTreeMap<String, (Abi, Vec<u8>)> = Default::default();
+        let mut known_contracts: BTreeMap<ArtifactId, (Abi, Vec<u8>)> = Default::default();
 
         // create a mapping of name => (abi, deployment code, Vec<library deployment code>)
         let mut deployable_contracts = DeployableContracts::default();
 
         foundry_utils::link(
-            &contracts,
+            BTreeMap::from_iter(contracts),
```
Comment (mattsse) [inline forge/src/multi_runner.rs:64]: .collect() should also work?

**Review by mattsse — APPROVED** [review]
lgtm,
pending ethers-rs bump

File: utils/src/lib.rs (hunk 2 above)
Comment (gakonst) [reply utils/src/lib.rs:1054]: eh this is fine
