### PR TITLE
Fix log formatting of decimal ints

### LINKED ISSUE #443: Correct formatting of decimals in ds-test logs
This is related to #361 which seems to have caused a regression [here](https://github.com/gakonst/foundry/blob/53984da48d2f03e9b777cec92fde860bf7361729/evm-adapters/src/sputnik/cheatcodes/cheatcode_handler.rs#L131).

The test was updated [here](https://github.com/gakonst/foundry/blob/53984da48d2f03e9b777cec92fde860bf7361729/evm-adapters/src/sputnik/cheatcodes/cheatcode_handler.rs#L1711) to pass.

Reverting these changes fixes the issue.

However, the outstanding issue remains. Assuming the output should match dapptools, then:

dapptools:
```
  -- log_named_decimal_int("decimal int", -1.0e18, 18)
  decimal int: -1.000000000000000000
```

forge:
```
  -- log_named_decimal_int("decimal int", -1.0e18, 18)
  decimal int: -1000000000000000000000000000000000000
```

I guess the # of trailing zeros for dapptools is arbitrary. @gakonst do you want to match dapptools exactly? I don't see any reason to have 18 trailing zeros.

Happy to take care of this

### PR DESCRIPTION
**Pull request by lattejed**
Fixes #443

Added some additional tests. Formatting matches dapptools.

### CODE REVIEW

**Comment by lattejed** [comment]
Same glitchy test again

File: evm-adapters/src/sputnik/cheatcodes/cheatcode_handler.rs [hunk 1]
```diff
@@ -114,14 +114,13 @@ pub(crate) fn convert_log(log: Log) -> Option<String> {
...
-            let val = val.trim().trim_start_matches('-');
+            use ethers::core::types::Sign;
+            let (sign, val) = inner.val.into_sign_and_abs();
             format!(
-                "{}: {}{:?}",
+                "{}: {}{}",
                 inner.key,
-                if neg { "-" } else { "" },
-                ethers::utils::parse_units(val, inner.decimals.as_u32()).unwrap()
+                if sign == Sign::Negative { "-" } else { "" },
```
Comment (mattsse) [inline evm-adapters/src/sputnik/cheatcodes/cheatcode_handler.rs:122]: sign should implement Display so it can be passed as is to format!

File: evm-adapters/src/sputnik/cheatcodes/cheatcode_handler.rs [hunk 2]
```diff
@@ -114,14 +114,13 @@ pub(crate) fn convert_log(log: Log) -> Option<String> {
...
+                ethers::utils::format_units(val, inner.decimals.as_u32()).unwrap()
```
Comment (mattsse) [inline evm-adapters/src/sputnik/cheatcodes/cheatcode_handler.rs:123]: can we bump this to as_u128? should be available I think

**Review by mattsse — CHANGES_REQUESTED** [review]

File: evm-adapters/src/sputnik/cheatcodes/cheatcode_handler.rs (hunk 1 above)
Comment (lattejed) [reply evm-adapters/src/sputnik/cheatcodes/cheatcode_handler.rs:122]: That would be idiomatic yeah. I'll add it in

File: evm-adapters/src/sputnik/cheatcodes/cheatcode_handler.rs (hunk 2 above)
Comment (lattejed) [reply evm-adapters/src/sputnik/cheatcodes/cheatcode_handler.rs:123]: The param is`TryInto<Units, ...>` and `Units` is u32

File: evm-adapters/src/sputnik/cheatcodes/cheatcode_handler.rs (hunk 1 above)
Comment (lattejed) [reply evm-adapters/src/sputnik/cheatcodes/cheatcode_handler.rs]: Never mind, it's already upstream 👍

**Review by gakonst — APPROVED** [review]
