### PR TITLE
fix: strip 0x prefix when parsing private key

### LINKED ISSUE #855: Cast wallet address `--private-key` parsing missing 0x prefix strip
### Component

Cast

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.1.0 (fb440ca 2022-03-07T17:34:05.082284540+00:00)

### What command(s) is the bug in?

cast wallet address --private-key

### Operating System

macOS (M1)

### Describe the bug

Private key parsing is missing a `0x` prefix strip in [`cli/src/opts/mod.rs`](https://github.com/gakonst/foundry/blob/master/cli/src/opts/mod.rs#L232-L238).

### PR DESCRIPTION
**Pull request by abigger87**
This PR closes #855 

## Motivation

Private key parsing is missing a `0x` prefix strip in [`cli/src/opts/mod.rs`](https://github.com/gakonst/foundry/blob/master/cli/src/opts/mod.rs#L232-L238).

## Solution

Use the `strip_prefix` utility to gracefully strip the `0x` prefix.

### CODE REVIEW

File: cli/src/opts/mod.rs [hunk 1]
```diff
@@ -231,7 +231,8 @@ impl Wallet {
 
     fn private_key(&self) -> Result<Option<LocalWallet>> {
         Ok(if let Some(ref private_key) = self.private_key {
-            Some(LocalWallet::from_str(private_key)?)
+            let privk = &private_key.strip_prefix("0x").unwrap_or(private_key);
+            Some(LocalWallet::from_str(privk)?)
         } else {
```
Comment (gakonst) [inline cli/src/opts/mod.rs:236]: nice - we only want this change, so can you remove the other 2 files that were touched?

**Review by gakonst — CHANGES_REQUESTED** [review]
