### PR TITLE
Capture reverted logs on failed tests

### LINKED ISSUE #282: logs not emitted on revert
I'm not seeing logs emitted when running `forge test --verbosity 3` and hitting a `revert()`

### PR DESCRIPTION
**Pull request by brockelmore**
Closes #282

### CODE REVIEW

File: evm-adapters/src/sputnik/cheatcodes/cheatcode_handler.rs [hunk 1]
```diff
@@ -95,6 +95,10 @@ impl<'a, 'b, B: Backend, P: PrecompileSet> SputnikExecutor<CheatcodeStackState<'
         U256::from(self.state().metadata().gasometer().gas())
     }
 
+    fn all_logs(&self) -> Vec<String> {
+        self.handler.state().all_logs.clone()
```
Comment (wilsoncusack) [inline evm-adapters/src/sputnik/cheatcodes/cheatcode_handler.rs:99]: Just learning: in the case of expected_revert, @gakonst had indicated a preference for using a reference rather than cloning. Would you want to use a reference here, as well?

File: evm-adapters/src/sputnik/cheatcodes/cheatcode_handler.rs [hunk 2]
```diff
@@ -705,6 +728,9 @@ impl<'a, 'b, B: Backend, P: PrecompileSet> CheatcodeStackExecutor<'a, 'b, B, P>
         let reason = self.execute(&mut runtime);
         // log::debug!(target: "evm", "Create execution using address {}: {:?}", address, reason);
 
+        let logs = self.logs()[..logs_len].to_vec();
```
Comment (wilsoncusack) [inline evm-adapters/src/sputnik/cheatcodes/cheatcode_handler.rs:731]: is it possible for logs_len to have changed since you defined it above 🤔

File: evm-adapters/src/sputnik/cheatcodes/cheatcode_handler.rs (hunk 1 above)
Comment (wilsoncusack) [reply evm-adapters/src/sputnik/cheatcodes/cheatcode_handler.rs:99]: also, in my case, clone actually didn't work for some reason. But I'm sure you know more!

File: forge/testdata/DebugLogsTest.sol [hunk 3]
```diff
@@ -24,6 +24,11 @@ contract DebugLogsTest is DSTest {
         emit log("three");
         fails.failure();
     }
+
+    function testFailWithRequire() public {
+        emit log("four");
+        require(false);
```
Comment (wilsoncusack) [inline forge/testdata/DebugLogsTest.sol:30]: I think priorly failures from `require` where still emitting but `revert` were not

**Review by gakonst — APPROVED** [review]
LGTM
