### PR TITLE
fix(config): support nested tables correctly

### LINKED ISSUE #793: yul optimizer doesn't seem to disable even with `yul = false` set under `optimizer_details` in `foundry.toml`
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.1.0 (6547691 2022-02-21T00:27:15.958524+00:00)

### What command(s) is the bug in?

forge build

### Operating System

macOS (M1)

### Describe the bug

am trying to build a foundry project that uses the [solidity-BigNumber](https://github.com/firoorg/solidity-BigNumber) library, which uses a lot of asm under the hood, specifically the `msize` instruction. when i run `forge build` i get the following error

```
SyntaxError: The msize instruction cannot be used when the Yul optimizer is activated because it can change its semantics. Either disable the Yul optimizer or do not use the instruction.
```

my `foundry.toml` looks like the following:
```
[default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = ['ds-test/=lib/ds-test/src']
optimizer = true

[optimizer_details]
yul = false
```

it seems as if forge is not respecting the `yul = false` option?

### PR DESCRIPTION
**Pull request by mattsse**
## Motivation
Closes #793

## Solution
This fixes a bug that resulted in the `optimizer_details` settings being ingored because they should be prefixed with the profile name according to toml standard.

updated docs accordingly

### CODE REVIEW

File: config/src/lib.rs [hunk 1]
```diff
@@ -621,7 +622,18 @@ impl Config {
...
+
+        if self.optimizer_details.is_some() {
+            // this is a hack to make nested tables work because this requires the config's profile
+            s = s
+                .replace("[optimizer_details]", &format!("[{}.optimizer_details]", self.profile))
+                .replace(
+                    "[optimizer_details.yulDetails]",
+                    &format!("[{}.optimizer_details.yulDetails]", self.profile),
+                );
+        }
```
Comment (gakonst) [inline config/src/lib.rs:635]: does this make it work even if the profile is not set?

**Review by gakonst — APPROVED** [review]

File: config/src/lib.rs (hunk 1 above)
Comment (mattsse) [reply config/src/lib.rs:635]: this is only really used in `forge config`, and there's always a profile, if not set via `FOUNDRY_PROFILE` it's always [default]
