### PR TITLE
fix: various revm fixes

### LINKED ISSUE #1042: Arithmetic overflow in lib.rs:38 causing forge test to fail
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (d4c615b 2022-03-24T01:05:20.744764+00:00)

### What command(s) is the bug in?

forge test

### Operating System

Linux

### Describe the bug

https://github.com/kalidao/multi-sig/actions/runs/2031799602

This pipeline passed against the version of forge from 3 nights ago, when re-run against the present version there is an error:

```
The application panicked (crashed).
Message:  arithmetic operation overflow
Location: /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/primitive-types-0.11.1/src/lib.rs:38

Backtrace omitted.
Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
/home/runner/work/_temp/618a42db-63b4-4979-9c12-59756dd77729.sh: line 1:  2851 Aborted                 (core dumped) forge test --optimize
```

This can be verified and debugged against that commit, or the present main branch of the kali-dao repo. I haven't been able to pin down where the regression was introduced, but it looks like it was in the last nightly.

### LINKED ISSUE #1058: Debugger panics on passing test case
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (e881b75 2022-03-25T00:03:11.855335753+00:00)

### What command(s) is the bug in?

`RUST_BACKTRACE=full forge test -vvvv --debug testPushNormalEmpty`

### Operating System

Linux

### Describe the bug

Attempting to run the debugger on a specific test case panics `forge`.

The [test case in question](https://github.com/jmcph4/albacore/blob/80f9f23e0876875b35659d80d1b2433403c843ee/src/test/RingBuffer.t.sol#L11) is reproduced here:

```solidity
    function testPushNormalEmpty() public {
        uint256 some_len = 12; /* arbitrary */
        bytes32 some_elem = bytes32(0);
        RingBuffer.RB_RingBuffer memory init_buf = RingBuffer.init(some_len);

        RingBuffer.RB_RingBuffer memory actual_buf = RingBuffer.push(
            init_buf,
            some_elem
        );

        bytes32[] memory expected_xs = new bytes32[](1);
        expected_xs[0] = some_elem;

        RingBuffer.RB_RingBuffer memory expected_buf = RingBuffer.RB_RingBuffer(
            expected_xs,
            some_len,
            0,
            1
        );

        assertEq(actual_buf.xs[0], expected_buf.xs[0]);
        assertEq(actual_buf.n, expected_buf.n);
        assertEq(actual_buf.read, expected_buf.read);
        assertEq(actual_buf.write, expected_buf.write);
    }
```

The test case succeeds:

```
$ forge test
[⠒] Compiling...
No files changed, compilation skipped

Running 2 tests for RingBufferTest.json:RingBufferTest
[PASS] testPushNormalEmpty() (gas: 14170)
[PASS] testPushNormalFull() (gas: 8289)
```

Attempting to invoke the debugger yields:

```
$ RUST_BACKTRACE=full forge test -vvvv --debug testPushNormalEmpty
[⠒] Compiling...
No files changed, compilation skipped
[⠊] Compiling...
[⠰] Compiling 3 files with 0.8.10
Compiler run successful
The application panicked (crashed).
Message:  unknown ic for pc
Location: /home/runner/work/foundry/foundry/evm/src/executor/inspector/debugger.rs:176

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   1: __libc_start_main<unknown>
      at ./csu/../csu/libc-start.c:308

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
Aborted
```

Some additional system information:
```
$ uname -a
Linux foobar 5.10.0-10-rt-amd64 #1 SMP PREEMPT_RT Debian 5.10.84-1 (2021-12-08) x86_64 GNU/Linux
$ rustup --version
rustup 1.24.3 (ce5817a94 2021-05-31)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.59.0 (9d1b2106e 2022-02-23)`
```

### PR DESCRIPTION
**Pull request by onbjerg**
Various fixes in executors and inspectors as well as REVM.

Companion PR: https://github.com/bluealloy/revm/pull/93

- Display delegatecall/staticcall/callcode/call in traces
- Display delegatecall/staticcall/callcode/call in traces
- Closes #1042 
- Closes #1058

### CODE REVIEW

**Comment by onbjerg** [comment]
Not sure if this is too verbose

image

**Comment by onbjerg** [comment]
The debugger now displays the call type as well, but the address is no longer necessarily the address of the storage - it is always the address of the code being executed.

image

File: evm/src/debug.rs [hunk 1]
```diff
@@ -85,14 +85,16 @@ pub struct DebugNode {
     pub children: Vec<usize>,
     /// Location in parent
     pub location: usize,
-    /// Address context
+    /// Execution context.
+    ///
+    /// Note that this is the address of the *code*, not necessarily the adddress of the storage.
```
Comment (mattsse) [inline evm/src/debug.rs:90]: nice!

**Review by mattsse — APPROVED** [review]
lgtm!

File: evm/src/trace/mod.rs [hunk 2]
```diff
@@ -333,11 +338,20 @@ impl fmt::Display for CallTrace {
...
+                _ => unreachable!(),
+            };
+
             let color = trace_color(self);
             write!(
                 f,
-                "[{}] {}::{}{}({})",
+                "[{}] {} {}::{}{}({})",
                 self.gas_cost,
+                Colour::Yellow.paint(action),
```
Comment (gakonst) [inline evm/src/trace/mod.rs:354]: can we make the color different from yellow, since that is what we use for contract creation with "new"?

File: evm/src/trace/mod.rs [hunk 3]
```diff
@@ -333,11 +338,20 @@ impl fmt::Display for CallTrace {
...
+                CallKind::CallCode => "callcode",
+                CallKind::DelegateCall => "delegatecall",
+                _ => unreachable!(),
+            };
+
             let color = trace_color(self);
             write!(
                 f,
-                "[{}] {}::{}{}({})",
+                "[{}] {} {}::{}{}({})",
```
Comment (gakonst) [inline evm/src/trace/mod.rs:352]: Can we put the call type after the name? Like "Contract::func() [staticcall]"

**Review by gakonst — APPROVED** [review]

**Review by gakonst — APPROVED** [review]
