### PR TITLE
REVM gas fixes

### LINKED ISSUE #812: forge test displays incorrect gas for function call, but displays correct gas in `forge test -vvvv`
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.1.0 (98f0771 2022-02-25T00:42:54.200449+00:00)

### What command(s) is the bug in?

forge test -vvvv

### Operating System

macOS (amd)

### Describe the bug

`forge test` claims zero gas is used on transfer, but if you rerun the command with verbosity level 4, it shows that there is a non-zero gas amount that was used. 

foundry-issue

test repo here:

https://github.com/anticlimactic/foundry-issue

install openzeppelin: `forge install openzeppelin/openzeppelin-contracts`

then run `forge test -vvvv`

### PR DESCRIPTION
**Pull request by onbjerg**
- Accounts for refunds in traces and the debugger
- Removes the gas stipend
- Merges `call_raw` and `call_raw_committing`

There's a weird issue with refunds/stipends that I will have to investigate more. The behaviour can be observed when running tests in https://github.com/anticlimactic/foundry-issue with traces on.

We should also consider upstreaming a flag or similar in REVM that just skips the stipend

Closes #812

### CODE REVIEW

File: forge/src/executor/mod.rs [hunk 1]
```diff
@@ -463,3 +454,9 @@ fn collect_inspector_states(stack: InspectorStack) -> InspectorData {
         debug: stack.debugger.map(|debugger| debugger.arena),
     }
 }
+
+/// Calculates the initial gas stipend for a transaction
+fn stipend(calldata: &[u8], spec: SpecId) -> u64 {
+    let non_zero_data_cost = if SpecId::enabled(spec, SpecId::ISTANBUL) { 16 } else { 68 };
```
Comment (gakonst) [inline forge/src/executor/mod.rs:460]: This should be 64 or 68?

Comment (onbjerg) [reply forge/src/executor/mod.rs:460]: Should it? I just took it from revm https://github.com/bluealloy/revm/blob/main/crates/revm/src/evm_impl.rs#L280

Comment (onbjerg) [reply forge/src/executor/mod.rs:460]: It's 68 per EIP-2028

Comment (gakonst) [reply forge/src/executor/mod.rs:460]: nvm

**Comment by onbjerg** [comment]
The issue with refunds:

image

This test (from https://github.com/anticlimactic/foundry-issue) has some refunds in it. As you can see the main trace has a final gas cost of 38234, but the test has a cost of 47792. I'm not sure what the discrepancy is caused by since traces should now account for refunds as well. If tests do not have any refunds, then this issue is not present.

On master the issue is even worse (I think we refund too much):

image

**Comment by onbjerg** [comment]
OK so I found out what the issue was with trace gas usage vs test gas usage when there was a refund, and a fix is pending in REVM: https://github.com/bluealloy/revm/pull/83

File: forge/src/executor/inspector/debugger.rs [hunk 2]
```diff
@@ -52,21 +52,19 @@ impl Debugger {
...
             let op = code[i];
             ic_map.insert(i, i - cumulative_push_size);
-            match OpCode::is_push(op) {
-                Some(push_size) => {
-                    // Skip the push bytes
-                    i += push_size as usize;
-                    cumulative_push_size += push_size as usize;
-                }
-                None => (),
+            if opcode_infos[op as usize].is_push {
```
Comment (gakonst) [inline forge/src/executor/inspector/debugger.rs:64]: let's add a note linking to how revm does it, in case we forget? https://github.com/bluealloy/revm/blob/007b8807b5ad7705d3cacce4d92b89d880a83301/crates/revm/src/interpreter/contract.rs#L114-L115
