### PR TITLE
fix(forge): fix errors on known function reverts

### LINKED ISSUE #296: feat(forge): Revert messages in traces
We should parse and print revert messages in a trace

### PR DESCRIPTION
**Pull request by brockelmore**
also should Close #296

### CODE REVIEW

File: evm-adapters/src/call_tracing.rs [hunk 1]
```diff
@@ -575,3 +594,56 @@ fn diff_score(bytecode1: &[u8], bytecode2: &[u8]) -> f64 {
...
+                        // assert
+                        Some("assert failure")
+                    }
+                    17 => {
+                        // safemath over/underflow
+                        Some("SafeMath over/underflow")
+                    }
+                    18 => {
+                        // divide by 0
+                        Some("Divide by 0")
```
Comment (transmissions11) [inline evm-adapters/src/call_tracing.rs:615]:
```suggestion
                        Some("Division by 0")
```

File: evm-adapters/src/call_tracing.rs [hunk 2]
```diff
@@ -575,3 +594,56 @@ fn diff_score(bytecode1: &[u8], bytecode2: &[u8]) -> f64 {
...
+            [78, 72, 123, 113] => {
+                // ref: https://soliditydeveloper.com/solidity-0.8
+                match data[data.len() - 1] {
+                    1 => {
+                        // assert
+                        Some("assert failure")
+                    }
+                    17 => {
+                        // safemath over/underflow
+                        Some("SafeMath over/underflow")
```
Comment (transmissions11) [inline evm-adapters/src/call_tracing.rs:611]:
```suggestion
                        Some("Arithmetic over/underflow")
```

camel cased "SafeMath" reminds me too much of OZ's lib

File: evm-adapters/src/call_tracing.rs [hunk 3]
```diff
@@ -575,3 +594,56 @@ fn diff_score(bytecode1: &[u8], bytecode2: &[u8]) -> f64 {
...
+fn decode_solidity_reverts(data: &[u8]) -> Option<&str> {
+    if data.len() >= 4 {
+        match data[0..4] {
+            // keccak(Panic(uint256))
+            [78, 72, 123, 113] => {
+                // ref: https://soliditydeveloper.com/solidity-0.8
+                match data[data.len() - 1] {
+                    1 => {
+                        // assert
+                        Some("assert failure")
```
Comment (transmissions11) [inline evm-adapters/src/call_tracing.rs:607]:
```suggestion
                        Some("Assertion violated")
```

File: evm-adapters/src/call_tracing.rs [hunk 4]
```diff
@@ -575,3 +594,56 @@ fn diff_score(bytecode1: &[u8], bytecode2: &[u8]) -> f64 {
...
+                        // index out of bounds
+                        Some("Index out of bounds")
+                    }
+                    65 => {
+                        // allocating too much memory or creating too large array
+                        Some("Memory allocation overflow")
+                    }
+                    81 => {
+                        // calling a zero initialized variable of internal function type
+                        Some("calling a zero initialized variable of internal function type")
```
Comment (transmissions11) [inline evm-adapters/src/call_tracing.rs:639]:
```suggestion
                        Some("Calling a zero initialized variable of internal function type")
```

File: evm-adapters/src/call_tracing.rs (hunk 1 above)
Comment (mds1) [reply evm-adapters/src/call_tracing.rs:615]: Could also be when modulo by zero
```suggestion
                        Some("Division by 0 / modulo by zero")
```

Comment (transmissions11) [reply evm-adapters/src/call_tracing.rs:615]: good point should def include that

File: evm-adapters/src/call_tracing.rs [hunk 5]
```diff
@@ -575,3 +620,56 @@ fn diff_score(bytecode1: &[u8], bytecode2: &[u8]) -> f64 {
     // println!("diff_score {}", diff_chars as f64 / cutoff_len as f64);
     diff_chars as f64 / cutoff_len as f64
 }
+
+fn decode_solidity_reverts(data: &[u8]) -> Option<&str> {
```
Comment (gakonst) [inline evm-adapters/src/call_tracing.rs:624]: I'd expand the logic of the Foundry utils function

**Review by gakonst — CHANGES_REQUESTED** [review]
LGTM but let's pull in these changes in the common helper function from foundry_utils?

File: evm-adapters/src/call_tracing.rs [hunk 6]
```diff
@@ -575,3 +620,56 @@ fn diff_score(bytecode1: &[u8], bytecode2: &[u8]) -> f64 {
...
+    if data.len() >= 4 {
```
Comment (mattsse) [inline evm-adapters/src/call_tracing.rs:625]: There is also https://doc.rust-lang.org/stable/std/vec/struct.Vec.html#method.starts_with

so this can be simplified a bit

```rust
if data.starts_with(&[78, 72, 123, 113]) {
   return None;
}

let msg = match data.last()? {
    1 => "Assertion violated",
    //--snip
   _ => return None
}

Some(msg)



```

**Review by gakonst — APPROVED** [review]

**Review by gakonst — CHANGES_REQUESTED** [review]
Seems like something broke in [this](https://github.com/gakonst/foundry/blob/brock/fix_reverts/evm-adapters/src/sputnik/cheatcodes/cheatcode_handler.rs#L1300) test? https://github.com/gakonst/foundry/runs/4622819837?check_suite_focus=true

```

---- sputnik::cheatcodes::cheatcode_handler::tests::ffi_fails_if_disabled stdout ----
thread 'sputnik::cheatcodes::cheatcode_handler::tests::ffi_fails_if_disabled' panicked at 'assertion failed: `(left == right)`
  left: `""`,
 right: `"ffi disabled: run again with --ffi if you want to allow tests to call external scripts"`', evm-adapters/src/sputnik/cheatcodes/cheatcode_handler.rs:1300:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
